### ISSUE TITLE
how much does it cost to analyze 200 games ?

### ISSUE THREAD

**Issue by vesper8** [jvsteiner/chessfunction#1]
Just curious as I've never tried serverless yet.. I found your project through chess-annotator and the idea of being able to easily offload multiple pgn game analysis to a serverless function on AWS sounds super cool.. but I'm curious if this is expensive for personal use? Like how much approximately does it cost per 100 games analyzed if you want to say spend no more than 1-2 minutes on each game ? A ballpark figure would be appreciated! Thanks!

Oh and while I have your attention.. does your function do anything extra or change the logic at all compared to chess-annotator or it's really just a wrapper around it that runs on serverless?

Many thanks for making and sharing it in any case! Sounds awesome!

**Comment by jvsteiner** [comment]
It's just a wrapper around chess-annotator.   I worked out that analyzing 1000 games for 2 mins would cost about $0.25 if there was no free tier, and that you could analyze 25000 games a month and still stay within the free tier.

**Comment by vesper8** [comment]
oh my! that's very affordable indeed! thanks a lot for chiming in

I hope I can resolve my issue detailed in https://github.com/jvsteiner/chessfunction/issues/2 so I can start using it soon

Cheers!

**Comment by jvsteiner** [comment]
sure no problem, glad you liked it
