### ISSUE TITLE
sequence item 0: expected str instance, dict found

### ISSUE THREAD

**Issue by vesper8** [jvsteiner/chessfunction#2]
Hello again!

So I decided to try running this today. This is my first time using Amazon Serverless so excuse me if I ask any stupid question. I know you said this ain't a tutorial but I'm still hoping you can help me out here.

So what I've done so far. I cloned this repository and changed the to/from email to mine. Then I installed serverless on my macbook. Then I created a new IAM user and assigned it Administrator Access and then configured sls with my credentials

Then I ran `sls deploy` from inside this cloned repository. It appears to have successfully uploaded the chessfunction to lambda

Finally I tried running it with a PGN file containing two games from lichess

When I run it with

`sls invoke -f annotate_games -p games.pgn`

I get this error:

```
Serverless: Deprecation warning: Starting with next major version, default value of provider.lambdaHashingVersion will be equal to "20201221"
            More Info: https://www.serverless.com/framework/docs/deprecations/#LAMBDA_HASHING_VERSION_V2
{
    "errorMessage": "sequence item 0: expected str instance, dict found",
    "errorType": "TypeError",
    "stackTrace": [
        "  File \"/var/task/src/handler.py\", line 57, in annotate_games\n    games = loop.run_until_complete(main(event))\n",
        "  File \"/var/lang/lib/python3.8/asyncio/base_events.py\", line 616, in run_until_complete\n    return future.result()\n",
        "  File \"/var/task/src/handler.py\", line 73, in main\n    analyzed_games = \"\".join(string_results)\n"
    ]
}

  Error --------------------------------------------------

  Error: Invoked function failed
      at AwsInvoke.log (/usr/local/lib/node_modules/serverless/lib/plugins/aws/invoke.js:123:13)
      at Object.invoke:invoke [as hook] (/usr/local/lib/node_modules/serverless/lib/plugins/aws/invoke.js:20:14)

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              15.5.0
     Framework Version:         2.19.0
     Plugin Version:            4.4.2
     SDK Version:               2.3.2
     Components Version:        3.4.7
```

This is my PGN contents:

```
[Event "Rated Blitz game"]
[Site "https://lichess.org/xxx"]
[Date "2021.01.11"]
[White "xxx"]
[Black "xxx"]
[Result "0-1"]
[UTCDate "2021.01.11"]
[UTCTime "11:20:00"]
[WhiteElo "1700"]
[BlackElo "1700"]
[WhiteRatingDiff "-5"]
[BlackRatingDiff "+6"]
[Variant "Standard"]
[TimeControl "180+2"]
[ECO "D00"]
[Termination "Time forfeit"]

1. d4 d5 2. Bf4 Nc6 3. Nf3 Bg4 4. e3 Nf6 5. h3 Bh5 6. a3 e6 7. Bd3 Bd6 8. Bxd6 cxd6 9. Nbd2 e5 10. dxe5 dxe5 11. Bb5 e4 12. g4 Nxg4 13. Ne5 Nxe5 14. Qxh5 Qf6 15. O-O-O O-O 16. f4 exf3 17. Rdf1 a6 18. Bd3 Nxd3+ 19. cxd3 Ne5 20. d4 Rac8+ 21. Kd1 Nd3 22. Rxf3 Nxb2+ 23. Ke2 Qe6 24. Rg1 Rc2 25. Rfg3 g6 0-1


[Event "Rated Blitz game"]
[Site "https://lichess.org/xxx"]
[Date "2021.01.10"]
[White "xxx"]
[Black "xxx"]
[Result "0-1"]
[UTCDate "2021.01.10"]
[UTCTime "15:20:00"]
[WhiteElo "1700"]
[BlackElo "1700"]
[WhiteRatingDiff "-7"]
[BlackRatingDiff "+6"]
[Variant "Standard"]
[TimeControl "180+2"]
[ECO "D00"]
[Termination "Normal"]

1. d4 d5 2. Bf4 Nc6 3. e3 Bf5 4. Nf3 e6 5. Nbd2 Bb4 6. c3 Bd6 7. Ne5 Nxe5 8. dxe5 Bc5 9. Nb3 Bb6 10. Nd4 Ne7 11. Qh5 Bxd4 12. exd4 Bg6 13. Qf3 O-O 14. h4 b6 15. h5 Be4 16. Qg3 Kh8 17. f3 Nf5 18. Qf2 g5 19. Bh2 Bxf3 20. gxf3 c5 21. Bd3 Nh6 22. Rg1 Rg8 23. O-O-O c4 24. Bc2 b5 25. f4 g4 26. Rg3 Rg7 27. Rdg1 a5 28. Bd1 Qh4 29. Qg2 Rag8 30. Rh1 Nf5 31. Bg1 Qxg3 32. Qxg3 Nxg3 33. Rh4 Ne4 34. Bc2 g3 35. Bxe4 dxe4 36. Rh3 g2 37. Kd2 Rg3 38. Ke2 Rxh3 0-1



```

Any idea why it's happening?

Many thanks!

**Comment by jvsteiner** [comment]
I cannot reproduce it.  Did you happen to set up you email address with AWS SES?  The only possibility I can think of is that when the email goes to send, there is an error there from SES, and something unexpected is then turning up where it shouldn't.

**Comment by vesper8** [comment]
I haven't set up my email with SES yet no.. but I'm also not passing the `-t Event` which as per your instructions should cause it to not use the email and just return the annotations to the CLI output?

The error happens almost immediately too

I realize now I had not set this parameter `aws ssm put-parameter --name /chessfunction/evaltime --value 1 --type String`

Upon setting it, it now waited 1 minute and this time it gave me an error related to my email.. I thought there would be a default value for the above parameter but I guess setting it is a requirement

Shouldn't the email issue not be an issue since I'm not passing `-t Event` ? 

Anyway I will verify my email now and it will probably start working afterwards

**Comment by vesper8** [comment]
So it works now.. it was a combination of not having set the evaltime parameter and not having verified my email address

I noticed however that it sends an email with a pgn attachment whether `-t Event` is set or not. If you don't include it then it blocks and waits for the output, but the email is triggered in either cases

**Comment by jvsteiner** [comment]
yup - this was desired behavior for me, feel free to adjust in your fork

**Comment by jvsteiner** [comment]
@vesper8  - in case you feel like documenting your setup experience, ie what you had to do with SES and setting the evaltime parameter it would be much appreciated.  `maybe you could write some few words into the README and make a PR? Would be very helpful!

**Comment by vesper8** [comment]
@jvsteiner hey cool, I just added a PR with basic setup instructions, as well as two other PRs that I am personally using and maybe you're interested in merging them, if not then no biggie

Thanks for introducing me to the wonderful world of serverless! I already have this working fully automated and triggered by my Laravel backend. It's so awesome to be able to analyze tons of games in tandem like this.

**Comment by jvsteiner** [comment]
super!  Glad you have enjoyed the project!
